option('cachedir',
       type : 'string',
       value : '/var/cache/pkgfile',
       description : 'default directory to store pkgfile data')

option('dbpath',
       type : 'string',
       value : '/var/lib/pacman',
       description : 'default location of the toplevel database directory')

option('systemd_units',
       type : 'boolean',
       value : true,
       description : 'install systemd units to system unit directory')
